
HT_CounterNames = {
    0x0A0A: ["Communication Mode Data", "交信モードデータ"],
    0x0A0B: ["Continuation Confirmation Data", "継続確認データ"],
    0x0A0C: ["End Confirmation Data", "終了確認データ"],
    0x0A0D: ["Download the Transmission Mode", "ダウンロード送信モード"],
    0x0A0E: ["Download the Confirmation Data", "ダウンロード確認データ"],
    0x0A1A: ["Identification Code Specification", "識別コード指定"],
    0x0AA0: ["Communication Command Record", ""],
    0x0B0A: ["Management Vending Machine Group", "自販機群管理"],
    0x0B0B: ["Data of Centre Phone Number", "センター電話番号データ"],
    0x0B0C: ["Data of Call Control", "発呼制御データ"],
    0x0B0D: ["Specification of Vending Machine Calling Time", "自販機発呼時刻指定"],
    0x0B0E: ["Version of Vending Machine Data", "自販機バージョンデータ"],
    0x0B1A: ["Supply Data (Packaged Goods)", "補給データパッケージ商品機"],
    0x0B1B: ["Merchandise Supply Data (Cup)", "商材補給データカップ機"],
    0x0B1C: ["Auxiliary Material Supply Data(Cup)", "補材補給データ カップ機"],
    0x0B2A: ["Full Number by Column", "コラム別満杯数 カップ機"],
    0x0B2B: ["Full Number by Merchandise", "商材別満杯数（カップ機)"],
    0x0B2C: ["Full Number by Auxiliary Material", "補材別満杯数（カップ機)"],
    0x0B3A: ["Malfunction, Monitor Code", "故障・モニターコード"],
    0x0B3B: ["Sold Out by Column (Packaged Goods)", "コラム別売切状態（パッケージ商品機)"],
    0x0B3C: ["Sold Out by Merchandise (Cup)", "商材別売切状態（カップ機)"],
    0x0B3D: ["Sold Out by Auxiliary Material (Cup)", "補材別売切状態（カップ機)"],
    0x0B3E: ["Stock Alarm Near-End Value(Packaged Goods)", "在庫アラームニアエンド値（パッケージ商品機)"],
    0x0B3F: ["Container Number by Column (Cup)", "コラム別容器番号（カップ機)"],
    0x0B4A: ["Cumulative Sales by Supply Column", "補給時コラム別累計販売数"],
    0x0B4B: ["Sales After Supply by Column(Packaged Goods)", "コラム別補給後販売数（パッケージ商品機)"],
    0x0B4C: ["Sales After Supply by Merchandise(Cup)", "商材別補給後販売数（カップ機）"],
    0x0B4D: ["Sales After Supply by Auxiliary Material (Cup)", "補材別補給後販売数（カップ機）"],
    0x0B5A: ["Data of Occurrence Time", "データ発生時刻"],
    0x0B5B: ["Time/Date of Configuration Data Change", "設定データ変化有り日時"],
    0x0B5C: ["Configuration of Sampling Period"	"サンプリング周期設定"],
    0x0B5D: ["Communication Log", "交信LOG"],
    0x0B6A: ["Cumulative When Recall", "回収時トータル累計"],
    0x0B6B: ["Cumulative Sales by Column when Recall", "回収時コラム別累計販売数"],
    0x0B6C: ["Cumulative Sales of Cash When Recall", "回収時コラム別現金売り累計販売数"],
    0x0B6D: ["Cumulative Sales of Prepaid Card by Column When Recall", "回収時コラム別プリペイドカード売り累計販売数"],
    0x0B6E: ["Cumulative Sales of Prepaid Card & Cash by Column When Recall", "回収時コラム別プリペイドカード・現金併用時累計販売数"],
    0x0B6F: ["Cumulative Sales of ID card by Column When Recall", "回収時コラム別IDカード売り累計販売数"],
    0x0B7A: ["Cumulative Sales of Free Bend by Column When Recall", "回収時コラム別フリーベンド累計販売数"],
    0x0B7B: ["Total Sales Amount of ID Card by Department When Recall", "回収時部署別IDカード売り累計販売金額"],
    0x0B7C: ["Total Insertion Number by Currency Denomination When Recall", "回収時金種別累計投入枚数"],
    0x0B7D: ["Total Payout Number by Currency DenominationWhen Recall", "回収時金種別累計払出枚数"],
    0x0B7E: ["Total Insertion Number by Large Currency Denomination When Recall", "回収時高額金種別累計投入枚数"],
    0x0B7F: ["Total Payout Number by Large Currency Denomination When Recall", "回収時高額金種別累計払出枚数"],
    0x0B8A: ["Sales by Column at the Time of Sampling", "サンプリング時コラム別販売数"],
    0x0B8B: ["The Presence or Absence of Change at the Time of Sampling", "サンプリング時釣り切れ有無"],
    0x0B8C: ["The Presence or Absence of Sold Out by Column at the Time of Sampling", "サンプリング時コラム別売り切れ有無（パッケージ商品）"],  # noqa
    0x0B8D: ["The Presence or Absence of Sold Out by Merchandise at the Time of Sampling (Cup)", "サンプリング時商材別売り切れ有無（カップ機）"],  # noqa
    0x0B8E: ["The Presence or Absence of Sold Out by Aux Material at the Time of Sampling (Cup)", "サンプリング時補材別売り切れ有無（カップ機）"],  # noqa
    0x0B8F: ["The Presence or Absence of Large Currency Denomination Change at the Time of Sampling", "サンプリング時高額金種釣り切れ有無"],  # noqa
    0x0BA0: ["Time", "時刻"],
    0x0BA1: ["Data of Vending Machine Management", "自販機管理データ"],
    0x0BB0: ["Data of Individual Vending Machine", "自販機個別データ"],
    0x0BB1: ["History of Failure code", "故障コード履歴"],
    0x0BB2: ["History of Monitor Code", "モニターコード履歴"],
    0x0BB3: ["Communication Log for Online", "オフライン用交信LOG"],
    0x0BB4: ["Cumulative Total", "トータル集計"],
    0x0BB5: ["Cumulative Total Backup", "トータル集計バックアップ"],
    0x0BB6: ["Cumulative Sales by Price", "価格別累計販売数"],
    0x0BB7: ["Sales by Date", "日別販売数"],
    0x0BB8: ["Merchandise Code (Cup)", "商材別コード（カップ機）"],
    0x0BB9: ["Auxiliary Material Code (Cup)", "補材別コード（カップ機）"],
    0x0BBA: ["Price of ID Card Sales by Department", "部署別IDカード売り販売金額"],
    0x0BBB: ["Backup Price of ID Card Sales by Department", "部署別IDカード売り販売金額バックアップ"],
    0x0BC0: ["Product Code", "商品コード"],
    0x0BC1: ["Classification Code (Packaged Goods)", "分類コード（パッケージ商品機）"],
    0x0BC2: ["Classification Code (Cup)", "分類コード（カップ機）"],
    0x0BC3: ["Cash Selling Unit Selling Price by Column", "コラム別現金売り販売単価"],
    0x0BC4: ["Sales by Column, コラム別販売数"],
    0x0BC5: ["Time of Sold Out by Column (Packaged Goods)", "コラム別売切時間（パッケージ商品）"],
    0x0BC6: ["Card Unit Sales Price by Column", "コラム別カード販売単価"],
    0x0BC7: ["Prepaid Card Unit Sales number by Column", "コラム別プリペイドカード売り販売数"],
    0x0BC8: ["Using Prepaid Card and Cash Unit Sales Price by Column", "コラム別プリペイドカード・現金併用時カード売り金額"],
    0x0BC9: ["ID Card sales number by Column", "コラム別IDカード売り販売数"],
    0x0BCA: ["Free vending sales number by Column", "コラム別フリーベンド販売数"],
    0x0BE0: ["Insertion Number by Currency Denomination", "金種別投入枚数"],
    0x0BE1: ["Emissions Number by Currency Denomination", "金種別排出枚数"],
    0x0BE2: ["Out of Change Time", "釣切時間"],
    0x0BE3: ["Vending Machine Operating Time", "自販機稼働時間"],
    0x0BE4: ["Sold-Out Monitor Time (Cup)", "売切モニター時間（カップ機）"],
    0x0BE5: ["Time of Sold-Out by Merchandise (Cup)", "商材別売切時間（カップ機）"],
    0x0BE6: ["Time of Sold-Out by Auxiliary Material (Cup)", "補材別売切時間（カップ機）"],
    0x0BE7: ["Insertion Number by Large Currency Denomination", "高額金種別投入枚数"],
    0x0BE8: ["Emissions Number by Large Currency Denomination", "高額金種別排出枚数"],
    0x0BE9: ["Out of Change Time by Large Currency Denomination", "高額金種別釣切時間"],
    0x0C0A: ["Cumulative Total", "トータル累計"],
    0x0C0B: ["Cumulative Sales by Column", "コラム別累計販売数"],
    0x0C0C: ["Cash Cumulative Sales by Column", "コラム別現金売り累計販売数"],
    0x0C0D: ["Prepaid Card Cumulative Sales by Column", "コラム別プリペイドカード売り累計販売数"],
    0x0C0E: ["Using Prepaid Card and Cash Cumulative Sales by Column", "コラム別プリペイドカード・現金併用時累計販売数"],
    0x0C0F: ["Cumulative Sales of ID Card by Column", "コラム別IDカード売り累計販売数"],
    0x0C1A: ["Cumulative Sales of Free Bend by Column", "コラム別フリーベンド累計販売数"],
    0x0C1B: ["Total Sales Amount of ID Card by Department", "部署別IDカード売り累計販売金額"],
    0x0C1C: ["Total Insertion Number by Currency Denomination", "金種別累計投入枚数"],
    0x0C1D: ["Total Emissions Number by Currency Denomination", "金種別累計払出枚数"],
    0x0C1E: ["Total Insertion Number by Large Currency Denomination", "高額金種別累計投入枚数"],
    0x0C1F: ["Total Emissions Number by Large Currency Denomination", "高額金種別累計排出枚数"],
    0x0C2A: ["Total Consumption by Merchandise (Cup)", "商材別累計消費量（カップ機）"],
    0x0C2B: ["Total Consumption by Auxiliary Material (Cup)", "補材別累計消費量（カップ機）"],
    0x0C2C: ["Total Supply Amount by Merchandise (Cup)", "商材別累計補給量（カップ機）"],
    0x0C2D: ["Total Supply Amount by Auxiliary Material (Cup)", "補材別累計補給量（カップ機）"],
    0x0C3A: ["Merchandise Stock Alarm Near-End Value (Cup)"	"商材在庫アラームニアエンド値（カップ機）"],
    0x0C3B: ["Auxiliary Material Stock Alarm Near-End Value (Cup)", "補材在庫アラームニアエンド値（カップ機）"],
    0x0C4A: ["General-Purpose Port Specification", "汎用ポート指定"],
}
